version: '3.7'
services:
    app:
        container_name: todo-app
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - '.:/app'
        ports:
            - '3000:3000'
